# Generated by Django 3.2.7 on 2021-09-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_finish_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
