# Generated by Django 3.2.7 on 2021-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedalTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(choices=[('1', 'Gold'), ('2', 'Silver'), ('3', 'Bronze')], default='3', max_length=10)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
