# Generated by Django 3.2.7 on 2021-09-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_medaltally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medaltally',
            name='country',
            field=models.CharField(choices=[('IND', 'India'), ('USA', 'USA'), ('UK', 'UK')], default='1', max_length=200),
        ),
    ]
