# Generated by Django 3.2.7 on 2021-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_medaltally_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheer_count', models.IntegerField(default=0)),
                ('country', models.CharField(choices=[('IND', 'India'), ('USA', 'USA'), ('UK', 'UK')], default='1', max_length=200)),
            ],
        ),
    ]
