# Generated by Django 3.2.7 on 2021-09-07 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_cheers'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
